dataset_path: "H:/data/tracking/testing"
detections_path: "data/point_rcnn/testing"
save_path: 'evaluation/results/sha_key/data'

# val [1,6,8,10,12,13,14,15,16,18,19]
# trainval [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
tracking_seqs: [1,6,8,10,12,13,14,15,16,18,19]

tracking_type: "Car"

state_func_covariance: 0.0008
measure_func_covariance: 0.00001
prediction_score_decay: 0.03
LiDAR_scanning_frequency: 10

max_prediction_num: 16
max_prediction_num_for_new_object: 3

input_score: 0
init_score: 0
update_score: 0
post_score: 3.

avg_score: True
rec_misses: True