dataset_path: "H:/data/tracking/training"
detections_path: "data/second_iou/training"
save_path: 'evaluation/results/sha_key/data'

# val [1,6,8,10,12,13,14,15,16,18,19]
# trainval [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
tracking_seqs: [1,6,8,10,12,13,14,15,16,18,19]

tracking_type: "Car"

state_func_covariance: 100
measure_func_covariance: 0.001
prediction_score_decay: 0.03
LiDAR_scanning_frequency: 10

max_prediction_num: 5
max_prediction_num_for_new_object: 3

input_score: -1.5
init_score: -1.5
update_score: -1.5
post_score: 0

avg_score: True
rec_misses: True